version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  api:
    build: .
    volumes:
      - ./api:/go/src/github.com/working/go-working-architecture
    ports:
      - "5000:8080"
    links:
      - db
      - elasticsearch

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    restart: unless-stopped

  elasticsearch:
    build: ./search
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200"
  nats:
    build: ./events
    restart: "always"
    ports:
      - "4200"
  services:
    build: .
    volumes:
      - ./api:/go/src/github.com/working/go-working-architecture/services
    links:
      - nats
    ports:
      - "4400"
  # redis:
  #   image: "redis:alpine"    
